# Generated by Django 5.1.3 on 2024-12-04 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleSheetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_access_token', models.CharField(max_length=255)),
                ('encrypted_refresh_token', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheet_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
