# Generated by Django 5.1.3 on 2024-12-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oauthsession_googlesheettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
