name: Django CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Starting deployment"
          
          # Navigate to the correct directory
          cd /django-workspace/contact-widget-backend
          
          # Ensure the repository is up to date
          git fetch origin
          git pull origin main
          
          # Activate virtual environment
          source /django-workspace/env/bin/activate
          
          # Install dependencies
          pip install -r requirements.txt
          
          # Apply migrations and collect static files
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput
          
          # Restart Apache server to apply changes
          sudo systemctl restart apache2
          
          echo "Deployment complete"
