# Generated by Django 5.1.3 on 2024-12-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='widget.widgetdata')),
            ],
        ),
    ]
