# Generated by Django 5.1.3 on 2024-12-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_submitteddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
