# Generated by Django 5.1.3 on 2024-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_widgetdata_sheet_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetdata',
            options={'verbose_name': 'Widget Data', 'verbose_name_plural': 'Widget Data'},
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='post_submit_action',
            field=models.CharField(choices=[('MSG', 'msg'), ('REDIRECT_URL', 'redirect_url'), ('HIDE_FORM', 'hide_form')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widgetdata',
            name='success_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
