# Generated by Django 5.1.3 on 2024-12-06 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0004_alter_widgetdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=255)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_fill', to='widget.widgetdata')),
            ],
        ),
    ]
