# Generated by Django 5.1.3 on 2024-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0005_prefill'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='spam_protection',
            field=models.BooleanField(default=False),
        ),
    ]
