# Generated by Django 5.1.3 on 2024-12-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0006_widgetdata_spam_protection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetdata',
            options={},
        ),
    ]
