# Generated by Django 5.1.3 on 2024-12-13 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0007_alter_widgetdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='email_notification',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='widget.emailnotification'),
            preserve_default=False,
        ),
    ]
