# Generated by Django 5.1.3 on 2024-12-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0008_emailnotification_widgetdata_email_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdata',
            name='email_notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget.emailnotification'),
        ),
    ]
