# Generated by Django 5.1.3 on 2024-12-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0009_alter_widgetdata_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='is_email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
