# Generated by Django 5.1.3 on 2024-12-13 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0010_widgetdata_is_email_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='admin/brand_logo')),
                ('name', models.CharField(max_length=255)),
                ('redirect_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='user/brand_logo')),
                ('name', models.CharField(max_length=255)),
                ('redirect_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='user_brand_info',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='widget.userbrandinfo'),
            preserve_default=False,
        ),
    ]
