# Generated by Django 5.1.3 on 2024-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0011_adminbrandinfo_userbrandinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrandinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='user/brand_logo'),
        ),
        migrations.AlterField(
            model_name='userbrandinfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
