# Generated by Django 5.1.3 on 2024-12-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0012_alter_userbrandinfo_logo_alter_userbrandinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdata',
            name='user_brand_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget.userbrandinfo'),
        ),
    ]
