# Generated by Django 5.1.3 on 2024-12-16 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0013_alter_widgetdata_user_brand_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('alignment', models.TextField(choices=[('S', 's'), ('C', 'c'), ('E', 'e')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template')),
                ('fields', models.JSONField(default=list)),
                ('header_enabled', models.BooleanField()),
                ('header_title', models.CharField(blank=True, max_length=255, null=True)),
                ('header_caption', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('embed_type', models.CharField(choices=[('I', 'i'), ('F', 'f')], default='I', max_length=1)),
                ('color_scheme', models.CharField(choices=[('D', 'd'), ('L', 'i')], default='L', max_length=1)),
                ('accent_color', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=50)),
                ('submit_button', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widget.submitbutton')),
            ],
        ),
    ]
