# Generated by Django 5.1.3 on 2024-12-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0014_submitbutton_formtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitbutton',
            name='alignment',
            field=models.TextField(choices=[('L', 'l'), ('C', 'c'), ('R', 'r')], default='L', max_length=1),
        ),
    ]
