# Generated by Django 5.1.3 on 2024-12-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0015_alter_submitbutton_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='color_scheme',
            field=models.CharField(choices=[('DARK', 'D'), ('LIGHT', 'I')], default='LIGHT', max_length=5),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='embed_type',
            field=models.CharField(choices=[('INLINE', 'I'), ('FLOATING_PANEL', 'F')], default='INLINE', max_length=14),
        ),
        migrations.AlterField(
            model_name='submitbutton',
            name='alignment',
            field=models.TextField(choices=[('LEFT', 'L'), ('CENTER', 'C'), ('RIGHT', 'R')], default='LEFT', max_length=6),
        ),
    ]
