# Generated by Django 5.1.3 on 2024-12-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0016_alter_formtemplate_color_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='color_scheme',
            field=models.CharField(choices=[('DARK', 'dark'), ('LIGHT', 'light')], default='LIGHT', max_length=5),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='embed_type',
            field=models.CharField(choices=[('INLINE', 'inline'), ('FLOATING_PANEL', 'floating_panel')], default='INLINE', max_length=14),
        ),
        migrations.AlterField(
            model_name='submitbutton',
            name='alignment',
            field=models.TextField(choices=[('LEFT', 'left'), ('CENTER', 'center'), ('RIGHT', 'right')], default='LEFT', max_length=6),
        ),
    ]
