# Generated by Django 5.1.3 on 2024-12-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0017_alter_formtemplate_color_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
