# Generated by Django 5.1.3 on 2024-12-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0018_alter_emailnotification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
