# Generated by Django 5.1.3 on 2024-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0019_widgetdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
