# Generated by Django 5.1.3 on 2024-12-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0020_widgetdata_description_widgetdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='script',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
