# Generated by Django 5.1.3 on 2024-12-27 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0021_widgetdata_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ButtonAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Outline'), ('F', 'Filled')], default='F', max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1)),
                ('button_color', models.CharField(default='#000', max_length=100)),
                ('label_color', models.CharField(default='#fff', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000', max_length=100)),
                ('font', models.PositiveSmallIntegerField(default=13)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('G', 'Grid'), ('C', 'Columns'), ('T', 'Table')], default='G', max_length=1)),
                ('picture', models.BooleanField(default=True)),
                ('title', models.BooleanField(default=True)),
                ('features', models.BooleanField(default=True)),
                ('price', models.BooleanField(default=True)),
                ('button', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EURO')], default='USD', max_length=3)),
                ('prefix', models.CharField(choices=[('NONE', 'None'), ('FROM', 'From'), ('AVERAGE', 'Average')], default='FROM', max_length=7)),
                ('amount', models.IntegerField()),
                ('postfix', models.CharField(choices=[('NONE', 'None'), ('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='MONTH', max_length=5)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000', max_length=100)),
                ('caption_color', models.CharField(default='#000', max_length=100)),
                ('font', models.PositiveSmallIntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='TitleAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000', max_length=100)),
                ('caption_color', models.CharField(default='#000', max_length=100)),
                ('font', models.PositiveSmallIntegerField(default=24)),
            ],
        ),
        migrations.AlterField(
            model_name='widgetdata',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.buttonappearance')),
                ('feature', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.featureappearance')),
                ('price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.priceappearance')),
                ('title', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.titleappearance')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='widget')),
                ('featured_column', models.BooleanField(default=False)),
                ('ribbon_text', models.CharField(blank=True, max_length=100, null=True)),
                ('skin_color', models.CharField(default='#000', max_length=100)),
                ('button', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.button')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='widget.content')),
                ('price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.price')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('icon', models.CharField(choices=[('N', 'None'), ('CH', 'Check'), ('CR', 'Cross'), ('M', 'Minus')], default='N', max_length=2)),
                ('hint', models.TextField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='widget.column')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('appearance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container', to='widget.appearance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget', to=settings.AUTH_USER_MODEL)),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.content')),
                ('layout', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.layout')),
            ],
        ),
    ]
