# Generated by Django 5.1.3 on 2024-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0022_button_buttonappearance_content_featureappearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='widget_type',
            field=models.CharField(choices=[('C', 'Contact_Form'), ('B', 'Form_Builder')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
