# Generated by Django 5.1.3 on 2024-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0023_widgetdata_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdata',
            name='widget_type',
            field=models.CharField(choices=[('C', 'Contact_Form'), ('F', 'Form_Builder')], max_length=1),
        ),
    ]
