# Generated by Django 5.1.3 on 2024-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0024_alter_widgetdata_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
