# Generated by Django 5.1.3 on 2024-12-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0025_container_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdata',
            name='widget_type',
            field=models.CharField(choices=[('CONTACT_US', 'Contact_Form'), ('FORM', 'Form_Builder')], max_length=10),
        ),
    ]
