# Generated by Django 5.1.3 on 2025-01-05 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0026_alter_widgetdata_widget_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=10)),
                ('value', models.TextField()),
                ('opacity', models.FloatField()),
                ('file', models.FileField(blank=True, null=True, upload_to='background_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=100, null=True)),
                ('text_color', models.CharField(blank=True, max_length=100, null=True)),
                ('border_radius', models.CharField(blank=True, max_length=50, null=True)),
                ('padding', models.CharField(blank=True, max_length=50, null=True)),
                ('font_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='font_family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='text_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='title_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('Inline', 'Inline'), ('Popup', 'Popup'), ('Sidebar', 'Sidebar')], max_length=10, null=True)),
                ('trigger', models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('Delay', 'Delay'), ('Scroll', 'Scroll'), ('Exit', 'Exit')], max_length=10, null=True)),
                ('position', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], max_length=5, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('background', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widget.background')),
                ('button_style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widget.buttonstyle')),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='display_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.displaysettings'),
        ),
    ]
