# Generated by Django 5.1.3 on 2025-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0027_background_buttonstyle_widgetdata_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='opacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='type',
            field=models.CharField(blank=True, choices=[('Image', 'Image'), ('Video', 'Video')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
