# Generated by Django 5.1.3 on 2025-01-07 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0028_alter_background_opacity_alter_background_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('URL', 'Url'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=5)),
                ('link_value', models.CharField(max_length=255)),
                ('new_tab', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='button',
            name='link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.link'),
        ),
    ]
