# Generated by Django 5.1.3 on 2025-01-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0029_link_alter_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='auto_responder_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='response_email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(choices=[('N', 'None'), ('CH', 'Check'), ('CR', 'Cross'), ('M', 'Minus')], default='CH', max_length=2),
        ),
    ]
