# Generated by Django 5.1.3 on 2025-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0030_emailnotification_auto_responder_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailnotification',
            name='response_email',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='response_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
