# Generated by Django 5.1.3 on 2025-01-07 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0031_remove_emailnotification_response_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
