# Generated by Django 5.1.3 on 2025-01-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0032_widgetdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='enable_google_integration',
            field=models.BooleanField(default=False),
        ),
    ]
