# Generated by Django 5.1.3 on 2025-01-07 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0033_widgetdata_enable_google_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='embed_type',
            field=models.CharField(choices=[('INLINE', 'inline'), ('FLOATING_PANEL', 'floating_panel'), ('POP_UP', 'pop_up')], default='INLINE', max_length=14),
        ),
    ]
