# Generated by Django 5.1.3 on 2025-01-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0036_appointmentwidget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentwidget',
            name='max_advance_booking',
        ),
        migrations.RemoveField(
            model_name='appointmentwidget',
            name='min_advance_booking',
        ),
        migrations.RemoveField(
            model_name='appointmentwidget',
            name='timezone',
        ),
    ]
