# Generated by Django 5.1.3 on 2025-01-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0037_remove_appointmentwidget_max_advance_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentwidget',
            name='business_picture',
            field=models.ImageField(upload_to='appointmentWidget'),
        ),
    ]
