# Generated by Django 5.1.3 on 2025-01-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0038_alter_appointmentwidget_business_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateSpecificHours',
        ),
    ]
