# Generated by Django 5.1.3 on 2025-01-10 21:52

import widget.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0039_delete_datespecifichours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayschedule',
            name='time_ranges',
        ),
        migrations.RemoveField(
            model_name='specialintervals',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='time_ranges',
            field=models.JSONField(default=list, validators=[widget.validators.validate_time_ranges]),
        ),
        migrations.DeleteModel(
            name='TimeRange',
        ),
        migrations.AddField(
            model_name='specialintervals',
            name='working_hours',
            field=models.JSONField(default=list, validators=[widget.validators.validate_time_ranges]),
        ),
    ]
