# Generated by Django 5.1.3 on 2025-01-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0040_remove_dayschedule_time_ranges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('alignment', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], max_length=10, null=True)),
                ('font_size', models.CharField(blank=True, max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('font_weight', models.CharField(blank=True, choices=[('normal', 'Normal'), ('medium', 'Medium'), ('semibold', 'SemiBold'), ('bold', 'Bold')], max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='button_position',
            field=models.CharField(blank=True, choices=[('top-right', 'Top Right'), ('top-center', 'Top Center'), ('top-left', 'Top Left'), ('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('center', 'Center')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='footer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.footer'),
        ),
        migrations.CreateModel(
            name='WidgetStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, choices=[('outline', 'Outline'), ('filled', 'Filled'), ('underline', 'Underline'), ('unstyled', 'Unstyled')], max_length=10, null=True)),
                ('background_color', models.CharField(blank=True, max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, max_length=50, null=True)),
                ('border_color', models.CharField(blank=True, max_length=50, null=True)),
                ('border_radius', models.CharField(blank=True, max_length=50, null=True)),
                ('border_width', models.CharField(blank=True, max_length=50, null=True)),
                ('font_size', models.CharField(blank=True, max_length=50, null=True)),
                ('padding', models.CharField(blank=True, max_length=50, null=True)),
                ('label_style', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget.labelstyle')),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='widget_style',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.widgetstyle'),
        ),
    ]
