# Generated by Django 5.1.3 on 2025-01-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0041_footer_labelstyle_displaysettings_button_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(max_length=10)),
                ('background_color', models.CharField(max_length=10)),
                ('text_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='widgetdata',
            name='widget_style',
        ),
        migrations.AddField(
            model_name='submitbutton',
            name='size',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitbutton',
            name='variant',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='default_language',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='submit_button',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.submitbutton'),
        ),
        migrations.AlterField(
            model_name='submitbutton',
            name='alignment',
            field=models.CharField(choices=[('LEFT', 'left'), ('CENTER', 'center'), ('RIGHT', 'right')], default='LEFT', max_length=6),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='theme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.theme'),
        ),
        migrations.DeleteModel(
            name='WidgetStyle',
        ),
    ]
