# Generated by Django 5.1.3 on 2025-01-17 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0042_theme_remove_widgetdata_widget_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentwidget',
            name='integration_google_sheets_auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.integrationgooglesheetsauth'),
        ),
    ]
