# Generated by Django 5.1.3 on 2025-01-17 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0043_alter_appointmentwidget_integration_google_sheets_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentwidget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
