# Generated by Django 5.1.3 on 2025-01-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0044_alter_appointmentwidget_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentwidget',
            name='integration_google_sheets_auth',
        ),
        migrations.DeleteModel(
            name='IntegrationGoogleSheetsAuth',
        ),
    ]
