# Generated by Django 5.1.3 on 2025-01-18 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0045_remove_appointmentwidget_integration_google_sheets_auth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCustomPictureSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_background', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('small', 'small'), ('large', 'large'), ('custom', 'custom')], max_length=10)),
                ('position', models.CharField(choices=[('top', 'top'), ('bottom', 'bottom')], max_length=10)),
                ('priority', models.CharField(choices=[('above-ribbon', 'above-ribbon'), ('below-ribbon', 'below-ribbon')], max_length=20)),
                ('fit', models.CharField(choices=[('cover', 'cover'), ('contain', 'contain'), ('fill', 'fill')], max_length=10)),
                ('alignment', models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=10)),
                ('custom_size', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingcustompicturesize')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='image_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetimagesettings'),
        ),
    ]
