# Generated by Django 5.1.3 on 2025-01-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0046_pricingcustompicturesize_pricingwidgetimagesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetimagesettings',
            name='alignment',
            field=models.CharField(choices=[('LEFT', 'LEFT'), ('CENTER', 'CENTER'), ('RIGHT', 'RIGHT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingwidgetimagesettings',
            name='fit',
            field=models.CharField(choices=[('COVER', 'COVER'), ('CONTAIN', 'CONTAIN'), ('FILL', 'FILL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingwidgetimagesettings',
            name='position',
            field=models.CharField(choices=[('TOP', 'TOP'), ('BOTTOM', 'BOTTOM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingwidgetimagesettings',
            name='priority',
            field=models.CharField(choices=[('ABOVE_RIBBON', 'ABOVE_RIBBON'), ('BELOW_RIBBON', 'BELOW_RIBBON')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingwidgetimagesettings',
            name='size',
            field=models.CharField(choices=[('SMALL', 'SMALL'), ('LARGE', 'SMALL'), ('CUSTOM', 'CUSTOM')], max_length=10),
        ),
    ]
