# Generated by Django 5.1.3 on 2025-01-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0047_alter_pricingwidgetimagesettings_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetimagesettings',
            name='size',
            field=models.CharField(choices=[('SMALL', 'SMALL'), ('LARGE', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('CUSTOM', 'CUSTOM')], max_length=10),
        ),
    ]
