# Generated by Django 5.1.3 on 2025-01-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0048_alter_pricingwidgetimagesettings_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='price',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='widget.appointmentprice'),
            preserve_default=False,
        ),
    ]
