# Generated by Django 5.1.3 on 2025-01-20 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0049_appointmentservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
