# Generated by Django 5.1.3 on 2025-01-21 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0051_appointmentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='auto_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='background',
            name='loop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='background',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buttonstyle',
            name='hover_background_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='delay',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='scroll_percentage',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='show_once',
            field=models.BooleanField(default=True),
        ),
    ]
