# Generated by Django 5.1.3 on 2025-01-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0052_background_auto_play_background_loop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
