# Generated by Django 5.1.3 on 2025-01-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0053_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
