# Generated by Django 5.1.3 on 2025-02-02 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0053_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='#000000', max_length=7)),
                ('text', models.CharField(default='#ffffff', max_length=7)),
                ('border', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ButtonSpacing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal', models.IntegerField(default=16)),
                ('vertical', models.IntegerField(default=8)),
                ('unit', models.CharField(default='px', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CornerRadius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=8)),
                ('unit', models.CharField(default='px', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('aspect_ratio', models.CharField(default='original', max_length=50)),
                ('corner_radius', models.CharField(default='square', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DarkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('start_color', models.CharField(default='#ffffff', max_length=7)),
                ('end_color', models.CharField(default='#000000', max_length=7)),
                ('angle', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='HoverColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='#333333', max_length=7)),
                ('text', models.CharField(default='#ffffff', max_length=7)),
                ('border', models.CharField(default='#333333', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='center', max_length=50)),
                ('size', models.CharField(default='cover', max_length=50)),
                ('repeat', models.CharField(default='no-repeat', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TitleStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('underline', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='submitbutton',
            name='full_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='mode',
            field=models.CharField(default='light', max_length=50),
        ),
        migrations.AddField(
            model_name='submitbutton',
            name='colors',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.buttoncolors'),
        ),
        migrations.AddField(
            model_name='submitbutton',
            name='spacing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.buttonspacing'),
        ),
        migrations.AddField(
            model_name='theme',
            name='corner_radius',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='theme_corner_radius', to='widget.cornerradius'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='dark_mode',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='theme_dark_mode', to='widget.darkmode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='darkmode',
            name='gradient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dark_mode_gradient', to='widget.gradient'),
        ),
        migrations.AddField(
            model_name='theme',
            name='gradient',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='theme_gradient', to='widget.gradient'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('alignment', models.CharField(default='center', max_length=50)),
                ('cover_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_cover_image', to='widget.coverimage')),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='header',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.header'),
        ),
        migrations.AddField(
            model_name='buttoncolors',
            name='hover',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hover_colors', to='widget.hovercolors'),
        ),
        migrations.AddField(
            model_name='background',
            name='image_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.imagesettings'),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='title_style',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.titlestyle'),
        ),
    ]
