# Generated by Django 5.1.3 on 2025-02-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0054_buttoncolors_buttonspacing_cornerradius_coverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncolors',
            name='hover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hover_colors', to='widget.hovercolors'),
        ),
    ]
