# Generated by Django 5.1.3 on 2025-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0054_alter_appointmentdata_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentwidget',
            name='font_url',
        ),
        migrations.AddField(
            model_name='appointmentwidget',
            name='font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
