# Generated by Django 5.1.3 on 2025-02-05 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0055_alter_buttoncolors_hover'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilderLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('columns', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='buttonstyle',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='custom_js',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='layout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.formbuilderlayout'),
        ),
    ]
