# Generated by Django 5.1.3 on 2025-01-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0055_remove_appointmentwidget_font_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgetdata',
            old_name='sheet_id',
            new_name='integration_google_sheets_id',
        ),
    ]
