# Generated by Django 5.1.3 on 2025-01-31 15:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0056_rename_sheet_id_widgetdata_integration_google_sheets_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingWidgetButtonFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveSmallIntegerField(verbose_name=18)),
                ('font_weight', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetButtonLinkV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('URL', 'URL'), ('EMAIL', 'EMAIL'), ('PHONE', 'PHONE')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('raw_value', models.CharField(max_length=255)),
                ('target', models.CharField(choices=[('_self', '_self'), ('_blank', '_blank')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetDiscountFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_weight', models.CharField(max_length=10)),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetDiscountV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('custom_label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetFeaturesV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='widget/images')),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetHeadFeaturesV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('hint', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetHeadTitleFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_weight', models.CharField(max_length=10)),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetLanguageV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('zh', 'Chinese'), ('ja', 'Japanese')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetOldPriceFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_weight', models.CharField(max_length=10)),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetOldPriceV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('custom_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetPriceCaptionFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_weight', models.CharField(max_length=10)),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetPriceFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_weight', models.CharField(max_length=10)),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetPriceV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_model', models.CharField(choices=[('fixed', 'fixed'), ('subscription', 'subscription'), ('from', 'from'), ('range', 'range'), ('per', 'per'), ('free', 'free'), ('custom', 'custom')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EURO')], max_length=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi-Annually'), ('annually', 'Annually')], max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('custom_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetTitleCaptionFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetTitleFontV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_weight', models.CharField(max_length=10)),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetTitleTextStyleV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField()),
                ('font_weight', models.CharField(max_length=10)),
                ('font_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetWidthV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=True)),
                ('custom_value', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetButtonV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('filled', 'filled'), ('contain', 'contain')], max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('label_color', models.CharField(max_length=20)),
                ('caption_color', models.CharField(max_length=20)),
                ('border_radius', models.PositiveSmallIntegerField(default=4)),
                ('horizontal_padding', models.PositiveSmallIntegerField(default=20)),
                ('vertical_padding', models.PositiveSmallIntegerField(default=10)),
                ('full_width', models.BooleanField(default=False)),
                ('size', models.PositiveSmallIntegerField()),
                ('font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetbuttonfontv2')),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetColumnV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='widget/images')),
                ('title', models.CharField(max_length=255)),
                ('title_caption', models.CharField(max_length=255)),
                ('price_caption', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=100)),
                ('button_caption', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=20)),
                ('highlight_label', models.CharField(max_length=100)),
                ('button_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetbuttonlinkv2')),
                ('features', models.ManyToManyField(to='widget.pricingwidgetfeaturesv2')),
                ('old_price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetoldpricev2')),
                ('price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetpricev2')),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetTableV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('head_title', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('columns', models.ManyToManyField(to='widget.pricingwidgetcolumnv2')),
                ('head_features', models.ManyToManyField(to='widget.pricingwidgetheadfeaturesv2')),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetSettingsV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_tables_mode', models.BooleanField()),
                ('layout', models.CharField(choices=[('comparison_table', 'comparison_table'), ('grid', 'grid'), ('classic_table', 'classic_table'), ('carousel', 'carousel')], max_length=20)),
                ('show_widget_title', models.BooleanField(default=True)),
                ('widget_title', models.CharField(max_length=100)),
                ('widget_title_caption', models.CharField(max_length=255)),
                ('widget_title_color', models.CharField(max_length=20)),
                ('widget_title_caption_color', models.CharField(max_length=20)),
                ('widget_title_link_color', models.CharField(max_length=20)),
                ('widget_title_alignment', models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], max_length=20)),
                ('widget_title_caption_font_size', models.CharField(max_length=20)),
                ('column_style', models.CharField(choices=[('style1', 'style1'), ('style2', 'style2'), ('style3', 'style3'), ('style4', 'style4'), ('style5', 'style5'), ('style6', 'style6')], max_length=10)),
                ('primary_color', models.CharField(max_length=20)),
                ('secondary_color', models.CharField(max_length=20)),
                ('font', models.CharField(max_length=50)),
                ('toggle_color', models.CharField(max_length=20)),
                ('column_corner_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('carousel_arrow_background_color', models.CharField(max_length=20)),
                ('carousel_arrow_color', models.CharField(max_length=20)),
                ('carousel_arrow_background_color_on_hover', models.CharField(max_length=20)),
                ('carousel_arrow_color_on_hover', models.CharField(max_length=20)),
                ('carousel_arrow_size', models.PositiveIntegerField(blank=True, null=True)),
                ('head_text_color', models.CharField(max_length=20)),
                ('head_background_color', models.CharField(max_length=20)),
                ('head_features_font_size', models.PositiveIntegerField()),
                ('show_title', models.BooleanField(default=True)),
                ('title_alignment', models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], max_length=20)),
                ('title_text_color', models.CharField(max_length=20)),
                ('title_caption_color', models.CharField(max_length=20)),
                ('show_features', models.BooleanField(default=True)),
                ('features_style', models.CharField(choices=[('plain', 'plain'), ('divided', 'divided'), ('striped', 'striped')], max_length=10)),
                ('features_align', models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], max_length=20)),
                ('features_font_size', models.PositiveIntegerField()),
                ('features_icon_color', models.CharField(max_length=20)),
                ('features_text_color', models.CharField(max_length=20)),
                ('show_price', models.BooleanField(default=True)),
                ('price_caption_color', models.CharField(max_length=20)),
                ('discount_text_color', models.CharField(max_length=20)),
                ('old_price_color', models.CharField(max_length=20)),
                ('price_align', models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], max_length=20)),
                ('price_color', models.CharField(max_length=20)),
                ('show_picture', models.BooleanField(default=True)),
                ('picture_aspect_ratio', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('show_button', models.BooleanField(default=True)),
                ('button_alignment', models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], max_length=20)),
                ('highlight_style_type', models.CharField(choices=[('ribbon', 'ribbon'), ('bar', 'bar')], max_length=20)),
                ('highlight_background_color', models.CharField(max_length=20)),
                ('highlight_text_color', models.CharField(max_length=20)),
                ('default_table', models.CharField(max_length=100)),
                ('button', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widget.pricingwidgetbuttonv2')),
                ('discount_font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetdiscountfontv2')),
                ('head_title_font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetheadtitlefontv2')),
                ('language', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetlanguagev2')),
                ('old_price_font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetoldpricefontv2')),
                ('price_caption_font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetpricecaptionfontv2')),
                ('price_font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetpricefontv2')),
                ('tables', models.ManyToManyField(to='widget.pricingwidgettablev2')),
                ('title_caption_font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgettitlecaptionfontv2')),
                ('title_font', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgettitlefontv2')),
                ('widget_title_text_style', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgettitletextstylev2')),
                ('width', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetwidthv2')),
            ],
        ),
        migrations.CreateModel(
            name='PricingWidgetV2',
            fields=[
                ('widget_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widget.pricingwidgetsettingsv2')),
            ],
        ),
    ]
