# Generated by Django 5.1.3 on 2025-01-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0057_pricingwidgetbuttonfontv2_pricingwidgetbuttonlinkv2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingwidgetdiscountfontv2',
            name='text_transform',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
