# Generated by Django 5.1.3 on 2025-01-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0059_pricingwidgetv2_user_delete_appointmentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetbuttonv2',
            name='mode',
            field=models.CharField(choices=[('filled', 'filled'), ('outline', 'outline')], max_length=20),
        ),
    ]
