# Generated by Django 5.1.3 on 2025-01-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0060_alter_pricingwidgetbuttonv2_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetbuttonfontv2',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=18),
        ),
    ]
