# Generated by Django 5.1.3 on 2025-02-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0061_alter_pricingwidgetbuttonfontv2_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetpricev2',
            name='custom_price',
            field=models.CharField(max_length=50),
        ),
    ]
