# Generated by Django 5.1.3 on 2025-02-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0062_alter_pricingwidgetpricev2_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='widget_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='widget_title_alignment',
            field=models.CharField(blank=True, choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='widget_title_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='widget_title_caption_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='widget_title_caption_font_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='widget_title_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='widget_title_link_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
