# Generated by Django 5.1.3 on 2025-02-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0063_alter_pricingwidgetsettingsv2_widget_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgettitletextstylev2',
            name='font_size',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='pricingwidgettitletextstylev2',
            name='font_style',
            field=models.CharField(default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingwidgettitletextstylev2',
            name='font_weight',
            field=models.CharField(default='bold', max_length=10),
        ),
    ]
