# Generated by Django 5.1.3 on 2025-02-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0064_alter_pricingwidgettitletextstylev2_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='font',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
