# Generated by Django 5.1.3 on 2025-02-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0065_alter_pricingwidgetsettingsv2_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetheadtitlefontv2',
            name='font_size',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='default_table',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='discount_text_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='features_icon_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='head_background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='head_features_font_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='head_text_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='highlight_background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='highlight_text_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='old_price_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='toggle_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgettitletextstylev2',
            name='font_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pricingwidgettitletextstylev2',
            name='font_style',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingwidgettitletextstylev2',
            name='font_weight',
            field=models.CharField(max_length=10),
        ),
    ]
