# Generated by Django 5.1.3 on 2025-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0066_alter_pricingwidgetheadtitlefontv2_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetsettingsv2',
            name='highlight_style_type',
            field=models.CharField(blank=True, choices=[('ribbon', 'ribbon'), ('bar', 'bar')], max_length=20, null=True),
        ),
    ]
