# Generated by Django 5.1.3 on 2025-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0067_alter_pricingwidgetsettingsv2_highlight_style_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingwidgettitlecaptionfontv2',
            name='font_weight',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
