# Generated by Django 5.1.3 on 2025-02-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0068_pricingwidgettitlecaptionfontv2_font_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingwidgetsettingsv2',
            name='discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.pricingwidgetdiscountv2'),
        ),
    ]
