# Generated by Django 5.1.3 on 2025-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0070_alter_pricingwidgetoldpricev2_custom_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetheadtitlefontv2',
            name='font_size',
            field=models.PositiveIntegerField(blank=True, default=24, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetheadtitlefontv2',
            name='font_style',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetheadtitlefontv2',
            name='font_weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
