# Generated by Django 5.1.3 on 2025-02-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0071_alter_pricingwidgetheadtitlefontv2_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetdiscountfontv2',
            name='font_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetdiscountfontv2',
            name='font_style',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetdiscountfontv2',
            name='font_weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingwidgetdiscountfontv2',
            name='text_transform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
