# Generated by Django 5.1.3 on 2025-02-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0072_alter_pricingwidgetdiscountfontv2_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingwidgetfeaturesv2',
            name='icon',
            field=models.FileField(upload_to='widget/images'),
        ),
    ]
