# Generated by Django 5.1.3 on 2025-02-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0056_formbuilderlayout_buttonstyle_icon_and_more'),
        ('widget', '0073_alter_pricingwidgetfeaturesv2_icon'),
    ]

    operations = [
    ]
