# Generated by Django 5.1.3 on 2025-02-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0074_merge_20250207_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilderPages',
            fields=[
                ('unique_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('field_ids', models.JSONField(blank=True, default=list, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('enum', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('back_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('submit_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('show_progress_bar', models.BooleanField(blank=True, null=True)),
                ('show_page_numbers', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('enum', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buttonstyle',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formbuilderlayout',
            name='pages',
            field=models.ManyToManyField(to='widget.formbuilderpages'),
        ),
        migrations.AlterField(
            model_name='displaysettings',
            name='mode',
            field=models.OneToOneField(choices=[('Inline', 'Inline'), ('Popup', 'Popup'), ('Sidebar', 'Sidebar')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.mode'),
        ),
        migrations.AddField(
            model_name='formbuilderlayout',
            name='navigation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.navigation'),
        ),
        migrations.AlterField(
            model_name='displaysettings',
            name='position',
            field=models.OneToOneField(choices=[('Inline', 'Inline'), ('Popup', 'Popup'), ('Sidebar', 'Sidebar')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.position'),
        ),
    ]
