# Generated by Django 5.1.3 on 2025-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0075_formbuilderpages_mode_navigation_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='enum',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
