# Generated by Django 5.1.3 on 2025-02-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0077_alter_position_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitbutton',
            name='colors',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.buttoncolors'),
        ),
        migrations.AlterField(
            model_name='submitbutton',
            name='spacing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='widget.buttonspacing'),
        ),
    ]
